language: python

jobs:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode12
      language: generic
      env: PYTHON=36
      # language: sh
      # addons:
      #   homebrew:
      #     packages:
      #     - python3
      #     - openssl
      #     update: true
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
        - python --version
        - pip install -U --upgrade pip
        - pip install -U pytest
        - pip install -U pytest-cov
        - pip install -U codecov
        - pip install -U virtualenv
        - wget https://github.com/samtools/bcftools/releases/download/1.10.2/bcftools-1.10.2.tar.bz2
        - tar -jvxf bcftools-1.10.2.tar.bz2 
        - cd bcftools-1.10.2 && make && sudo make install && cd ..
        - wget https://github.com/samtools/htslib/releases/download/1.10.2/htslib-1.10.2.tar.bz2
        - tar -jvxf htslib-1.10.2.tar.bz2
        - cd htslib-1.10.2 && make && sudo make install && cd ..

before_install: # for linux jobs
  - sudo apt-get update
    # attempt to get cyvcf2 working, it requires a SHA256 'symbol'
  - sudo apt-get -y install -y libcrypto++-dev libssl-dev libcurl4-openssl-dev
  - python --version
  - pip install -U --upgrade pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  - pip install -U virtualenv
  - wget https://github.com/samtools/bcftools/releases/download/1.10.2/bcftools-1.10.2.tar.bz2
  - tar -jvxf bcftools-1.10.2.tar.bz2 
  - cd bcftools-1.10.2 && make && sudo make install && cd ..
  - wget https://github.com/samtools/htslib/releases/download/1.10.2/htslib-1.10.2.tar.bz2
  - tar -jvxf htslib-1.10.2.tar.bz2
  - cd htslib-1.10.2 && make && sudo make install && cd ..

install:
  - pip install .
  
script:
  - python -m pytest --cov=.
  - sh test/cmdline_tests.sh

after_success:
  - codecov
